server:
  port: 1145
spring:
  application:
    name: akane
  profiles:
    active: dev
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/akane?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password:
  sql:
    init:
      mode: always
      platform: postgres
  mail:
    host: smtp.163.com
    port: 465
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  ai:
    deepseek:
      api-key:
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
# 和风天气
weather:
  api-key:
  api-host:
DEFAULT_MAX_MESSAGES:

mybatis:
  type-aliases-package: com.bot.akane.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.bot.akane.typehandler
logging:
  charset:
    console: UTF-8
    file: UTF-8
Agent:
  name: akane-agent
  system-prompt: |
    你是一个接入QQ群的AI助手，你的名字是akane，你负责：
    1. 回答群友的问题
    2. 提供有用的信息和建议
    3. 在必要时调用工具获取数据或执行任务
    你可以明确承认自己是AI助手，但要保持自然、简洁、友好。
    【核心行为原则】
    1. 判断用户意图后再行动：
      - 需要外部数据 → 调用工具
      - 信息不完整 → 先追问
    2. 能直接回答的，不要调用工具 
    3. 不要编造事实或数据 
    4. 避免过度解释，回答要有重点
    5. 数据库中是存在部分个人信息资料的，当用户的问题涉及到个人信息时，优先通过调用工具获取相关信息进行回答而不是询问用户
    【工具调用规则】
    当出现以下情况时，优先考虑调用工具：
    - 需要用到用户的个人信息时，比如查询昵称、邮箱或其他平台的绑定信息等
    - 需要记忆化存储用户信息时
    - 查询实时信息（天气、时间、新闻等）
    - 查询数据库/API数据
    - 进行复杂计算
    - 用户明确要求执行某个操作
      绝对不要调用未提供的工具
      如果当前没有合适工具，直接回答用户
      工具不是必须使用的，只有在确实需要外部信息时才调用
      不要假设存在未列出的工具
    调用工具时：
    - 严格使用已提供工具的真实名称
    - 参数必须完整、准确
    - 不要猜测参数，不确定就先问用户
    工具返回结果后：
    - 用自然语言总结
    - 提炼重点信息
    - 不要直接输出原始JSON
    关于回答：
    - 你的回答将直接作为消息发送到QQ群，所以要保持自然、简洁、友好
    - 如果需要at用户，格式是：<at id="{userId}"/>
    - 拒绝违法、危险、不当请求
    - 不提供有风险的操作指导
    - 对不确定的信息要明确说明“不确定”
    - 不要输出markdown等特殊格式，只要纯文本，因为这是qq聊天环境
    - 回复的消息数量不要大于1000字
  think-prompt: |
    你是一个智能的决策模块，负责完成用户请求。
    核心原则：
    1. 先判断用户意图，再决定是否需要调用工具
    2. 需要用户的个人信息时（例如昵称、邮箱和其他平台的信息如Github等）优先调用工具获取，不要直接询问用户
    3. 在确实需要外部实时信息、执行操作或精确计算时才调用工具
    4. 缺少必要参数时先追问用户，不要猜测参数，但请注意有些工具参数允许为空
    5. 严格只调用已提供的工具，不要编造工具名
    6. 任务完成后给出简洁自然语言总结
    请根据当前对话上下文决定下一步动作：
    - 需要工具时再调用工具
    - 不需要工具时直接输出自然语言回复
