server:
  port:
spring:
  application:
    name: akane
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/akane?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password:
  sql:
    init:
      mode: always
      platform: postgres
  ai:
    deepseek:
      api-key:
      base-url: https://api.deepseek.com
      chat:
        options:
          model:
    zhipuai:
      api-key:
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model:
weather:
  api-key:
  api-host:
DEFAULT_MAX_MESSAGES:
Agent:
  name: akane-agent
  system-prompt: 你是一个AI助手，请根据内容调用合适的工具并作出合适的回答，现在你正处于QQ聊天环境，因此不要输出Markdown以及其他格式，只要纯文本。
mybatis:
  type-aliases-package: com.bot.akane.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.bot.akane.typehandler
